name: Format

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'

jobs:
  main:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - '.'

    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.5.0
        with:
          clang-format-version: 13
          check-path: ${{ matrix.path }}
