name: Test

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            os: ubuntu-latest,
            cc: gcc-9, cxx: g++-9,
            cmake_args: "",
          }
          - {
            os: ubuntu-latest,
            cc: gcc-10, cxx: g++-10,
            cmake_args: "",
          }
          - {
            os: ubuntu-latest,
            cc: clang-11, cxx: clang++-11,
            cmake_args: "",
          }
          - {
            os: ubuntu-latest,
            cc: clang-12, cxx: clang++-12,
            cmake_args: "",
          }
          - {
            os: macos-latest,
            cc: clang, cxx: clang++,
            cmake_args: "-DYACLIB_DEFINITIONS=/DYACLIB_CI_SLOWDOWN=10",
          }
          - {
            os: windows-latest,
            cc: cl, cxx: cl,
            cmake_args: "",
          }
        build_type: [ RelWithDebInfo, Debug ]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run:
          mkdir build &&
          cd build &&
          cmake ..
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=${{ matrix.config.cc }}
          -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -DYACLIB_BUILD_TESTING=ON
          ${{ matrix.config.cmake_args }}

      - name: Build
        run:
          cmake --build build --config ${{ matrix.build_type }}

      - name: Test
        run:
          cd build &&
          ctest --output-on-failure -C ${{ matrix.build_type }} -V
